// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.15.7
// source: proto/pokemon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"` // Pokemon name or PKMN ID
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{0}
}

func (x *SearchRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Pokemon struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32            `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name    string           `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Sprites *Pokemon_Sprites `protobuf:"bytes,3,opt,name=sprites,proto3" json:"sprites,omitempty"`
	Types   []*Pokemon_Type  `protobuf:"bytes,4,rep,name=types,proto3" json:"types,omitempty"`
}

func (x *Pokemon) Reset() {
	*x = Pokemon{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pokemon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon) ProtoMessage() {}

func (x *Pokemon) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon.ProtoReflect.Descriptor instead.
func (*Pokemon) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{1}
}

func (x *Pokemon) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Pokemon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pokemon) GetSprites() *Pokemon_Sprites {
	if x != nil {
		return x.Sprites
	}
	return nil
}

func (x *Pokemon) GetTypes() []*Pokemon_Type {
	if x != nil {
		return x.Types
	}
	return nil
}

type Pokemon_Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type *Pokemon_Type_Type `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
}

func (x *Pokemon_Type) Reset() {
	*x = Pokemon_Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pokemon_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon_Type) ProtoMessage() {}

func (x *Pokemon_Type) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon_Type.ProtoReflect.Descriptor instead.
func (*Pokemon_Type) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Pokemon_Type) GetType() *Pokemon_Type_Type {
	if x != nil {
		return x.Type
	}
	return nil
}

type Pokemon_Sprites struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BackDefault  string `protobuf:"bytes,1,opt,name=back_default,json=backDefault,proto3" json:"back_default,omitempty"`
	BackShiny    string `protobuf:"bytes,2,opt,name=back_shiny,json=backShiny,proto3" json:"back_shiny,omitempty"`
	FrontDefault string `protobuf:"bytes,3,opt,name=front_default,json=frontDefault,proto3" json:"front_default,omitempty"`
	FrontShiny   string `protobuf:"bytes,4,opt,name=front_shiny,json=frontShiny,proto3" json:"front_shiny,omitempty"`
}

func (x *Pokemon_Sprites) Reset() {
	*x = Pokemon_Sprites{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pokemon_Sprites) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon_Sprites) ProtoMessage() {}

func (x *Pokemon_Sprites) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon_Sprites.ProtoReflect.Descriptor instead.
func (*Pokemon_Sprites) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{1, 1}
}

func (x *Pokemon_Sprites) GetBackDefault() string {
	if x != nil {
		return x.BackDefault
	}
	return ""
}

func (x *Pokemon_Sprites) GetBackShiny() string {
	if x != nil {
		return x.BackShiny
	}
	return ""
}

func (x *Pokemon_Sprites) GetFrontDefault() string {
	if x != nil {
		return x.FrontDefault
	}
	return ""
}

func (x *Pokemon_Sprites) GetFrontShiny() string {
	if x != nil {
		return x.FrontShiny
	}
	return ""
}

type Pokemon_Type_Type struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Pokemon_Type_Type) Reset() {
	*x = Pokemon_Type_Type{}
	if protoimpl.UnsafeEnabled {
		mi := &file_proto_pokemon_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pokemon_Type_Type) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pokemon_Type_Type) ProtoMessage() {}

func (x *Pokemon_Type_Type) ProtoReflect() protoreflect.Message {
	mi := &file_proto_pokemon_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pokemon_Type_Type.ProtoReflect.Descriptor instead.
func (*Pokemon_Type_Type) Descriptor() ([]byte, []int) {
	return file_proto_pokemon_proto_rawDescGZIP(), []int{1, 0, 0}
}

func (x *Pokemon_Type_Type) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_proto_pokemon_proto protoreflect.FileDescriptor

var file_proto_pokemon_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x70, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x23, 0x0a, 0x0d, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xde, 0x02, 0x0a, 0x07, 0x50,
	0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x2a, 0x0a, 0x07, 0x73, 0x70,
	0x72, 0x69, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x50, 0x6f,
	0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x53, 0x70, 0x72, 0x69, 0x74, 0x65, 0x73, 0x52, 0x07, 0x73,
	0x70, 0x72, 0x69, 0x74, 0x65, 0x73, 0x12, 0x23, 0x0a, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x18,
	0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e,
	0x54, 0x79, 0x70, 0x65, 0x52, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x1a, 0x4a, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x12, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65,
	0x2e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x1a, 0x1a, 0x0a, 0x04, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x1a, 0x91, 0x01, 0x0a, 0x07, 0x53, 0x70, 0x72, 0x69,
	0x74, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x62, 0x61, 0x63, 0x6b, 0x44,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x61, 0x63, 0x6b, 0x5f, 0x73,
	0x68, 0x69, 0x6e, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x62, 0x61, 0x63, 0x6b,
	0x53, 0x68, 0x69, 0x6e, 0x79, 0x12, 0x23, 0x0a, 0x0d, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x5f, 0x64,
	0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x66, 0x72,
	0x6f, 0x6e, 0x74, 0x5f, 0x73, 0x68, 0x69, 0x6e, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0a, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x53, 0x68, 0x69, 0x6e, 0x79, 0x32, 0x31, 0x0a, 0x07, 0x50,
	0x6f, 0x6b, 0x65, 0x64, 0x65, 0x78, 0x12, 0x26, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x50, 0x6f, 0x6b,
	0x65, 0x6d, 0x6f, 0x6e, 0x12, 0x0e, 0x2e, 0x53, 0x65, 0x61, 0x72, 0x63, 0x68, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x08, 0x2e, 0x50, 0x6f, 0x6b, 0x65, 0x6d, 0x6f, 0x6e, 0x42, 0x31,
	0x5a, 0x2f, 0x2e, 0x2e, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4a, 0x50, 0x46, 0x33, 0x4e, 0x39, 0x39, 0x38, 0x2f, 0x67, 0x52, 0x50, 0x43, 0x2d, 0x47, 0x6f,
	0x6c, 0x61, 0x6e, 0x67, 0x2d, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_proto_pokemon_proto_rawDescOnce sync.Once
	file_proto_pokemon_proto_rawDescData = file_proto_pokemon_proto_rawDesc
)

func file_proto_pokemon_proto_rawDescGZIP() []byte {
	file_proto_pokemon_proto_rawDescOnce.Do(func() {
		file_proto_pokemon_proto_rawDescData = protoimpl.X.CompressGZIP(file_proto_pokemon_proto_rawDescData)
	})
	return file_proto_pokemon_proto_rawDescData
}

var file_proto_pokemon_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_proto_pokemon_proto_goTypes = []interface{}{
	(*SearchRequest)(nil),     // 0: SearchRequest
	(*Pokemon)(nil),           // 1: Pokemon
	(*Pokemon_Type)(nil),      // 2: Pokemon.Type
	(*Pokemon_Sprites)(nil),   // 3: Pokemon.Sprites
	(*Pokemon_Type_Type)(nil), // 4: Pokemon.Type.Type
}
var file_proto_pokemon_proto_depIdxs = []int32{
	3, // 0: Pokemon.sprites:type_name -> Pokemon.Sprites
	2, // 1: Pokemon.types:type_name -> Pokemon.Type
	4, // 2: Pokemon.Type.type:type_name -> Pokemon.Type.Type
	0, // 3: Pokedex.GetPokemon:input_type -> SearchRequest
	1, // 4: Pokedex.GetPokemon:output_type -> Pokemon
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_pokemon_proto_init() }
func file_proto_pokemon_proto_init() {
	if File_proto_pokemon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_proto_pokemon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SearchRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pokemon); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pokemon_Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pokemon_Sprites); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_proto_pokemon_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pokemon_Type_Type); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_proto_pokemon_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_pokemon_proto_goTypes,
		DependencyIndexes: file_proto_pokemon_proto_depIdxs,
		MessageInfos:      file_proto_pokemon_proto_msgTypes,
	}.Build()
	File_proto_pokemon_proto = out.File
	file_proto_pokemon_proto_rawDesc = nil
	file_proto_pokemon_proto_goTypes = nil
	file_proto_pokemon_proto_depIdxs = nil
}
